### PR TITLE
Fixed filesystem variable in docker_registry_module

### PR DESCRIPTION
**Pull request by MarcosGabilondo**
Fixed filesystem variable in docker_registry_module

### CODE REVIEW

**Comment by ElvenSpellmaker** [comment]
Why are we changing from `@` to the `[]` format here?

**Comment by MarcosGabilondo** [comment]
Because with @ the module can't read the variables of all the module. It is onlky taking the variables that are declared in the class and you need to use the variables that are declared in the params.pp file.

**Comment by ElvenSpellmaker** [comment]
Hmm, we haven't had to use this syntax so far, and according to this file, the variable _is_ in scope already?

https://github.com/ve-interactive/puppet-docker_registry/blob/master/manifests/config.pp#L5

**Comment by MarcosGabilondo** [comment]
Yes, I saw it and it's weird, but without this change the module don't get the correct value in the variable.

**Comment by ElvenSpellmaker** [comment]
The problem with doing it this way is that it can no longer be overridden, as long as we're all aware it's OK I suppose.

**Pull request merged**
